# Generated by Django 4.0.1 on 2026-02-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_customer_affiliate_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
