# Generated by Django 4.0.1 on 2026-02-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_setting_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='disk',
        ),
        migrations.AddField(
            model_name='customer',
            name='first_order_amount',
            field=models.FloatField(default=0),
        ),
    ]
